/** @type {Record<string, string[]>} */
export const gematriaMethods = {
	standard: ['standard'],
	normal: ['standard'],
	regular: ['standard'],
	hechrachi: ['standard'],
	absolute: ['standard'],
	normative: ['standard'],
	gematria: ['standard'],
	gematriah: ['standard'],
	'gematria value': ['standard'],
	'gematria number': ['standard'],
	gimatria: ['standard'],
	gimatriah: ['standard'],
	gematriya: ['standard'],
	gematriyah: ['standard'],
	גמטריא: ['standard'],
	גימטריה: ['standard'],
	'standard value': ['standard'],
	'normal value': ['standard'],
	'regular value': ['standard'],
	'absolute value': ['standard'],
	'normative value': ['standard'],
	'face value': ['standard'],
	'mispar hapanim': ['standard'],
	'mispar hapnim': ['standard'],
	'mispar hechrachi': ['standard'],
	'mispar hechrachi (standard)': ['standard'],
	'מספר הפנים': ['standard'],
	'מספר החרכי': ['standard'],
	החרכי: ['standard'],
	gadol: ['gadol'],
	large: ['gadol'],
	'large sofit': ['gadol'],
	'large final': ['gadol'],
	'large value': ['gadol'],
	'mispar gadol': ['gadol'],
	'mispar gadol (large sofit)': ['gadol'],
	'מספר גדול': ['gadol'],
	גדול: ['gadol'],
	siduri: ['siduri'],
	ordinal: ['siduri'],
	'ordinal value': ['siduri'],
	'ordinal number': ['siduri'],
	'mispar siduri': ['siduri'],
	'mispar siduri (ordinal)': ['siduri'],
	'מספר סידורי': ['siduri'],
	סידורי: ['siduri'],
	katan: ['katan'],
	small: ['katan'],
	reduced: ['katan'],
	'reduced value': ['katan'],
	'reduced number': ['katan'],
	'mispar katan': ['katan'],
	'mispar katan (reduced)': ['katan'],
	'mispar meugal': ['katan'],
	'mispar meugel': ['katan'],
	"mispar me'ugal": ['katan'],
	'מספר קטן': ['katan'],
	קטן: ['katan'],
	'מספר מעוגל': ['katan'],
	מעוגל: ['katan'],
	perati: ['perati'],
	haperati: ['perati'],
	'hamerubah haperati': ['perati'],
	'mispar hamerubah haperati': ['perati'],
	hamerubah: ['perati', 'hamerubah_haklali'],
	squared: ['perati', 'hamerubah_haklali'],
	'squared values': ['perati'],
	'squared numbers': ['perati'],
	'mispar perati': ['perati'],
	'mispar haperati': ['perati'],
	'mispar perati (squared values)': ['perati'],
	'מספר הפרטי': ['perati'],
	הפרטי: ['perati'],
	'מספר המרובע הפרטי': ['perati'],
	'המרובע הפרטי': ['perati'],
	'מספר פרטי': ['perati'],
	פרטי: ['perati'],
	המרובע: ['perati', 'hamerubah_haklali'],
	shemi: ['shemi'],
	full: ['shemi'],
	'full name': ['shemi'],
	'full value': ['shemi'],
	'full number': ['shemi'],
	'mispar shemi': ['shemi'],
	'mispar milui': ['shemi'],
	'mispar miluy': ['shemi'],
	milui: ['shemi'],
	miluy: ['shemi'],
	'mispar shemi / milui (full name)': ['shemi'],
	'מספר שמי': ['shemi'],
	שמי: ['shemi'],
	'מספר מילוי': ['shemi'],
	מילוי: ['shemi'],
	neelam: ['neelam'],
	hidden: ['neelam'],
	'hidden value': ['neelam'],
	'hidden number': ['neelam'],
	'mispar neelam': ['neelam'],
	"mispar ne'elam": ['neelam'],
	'מספר נעלם': ['neelam'],
	נעלם: ['neelam'],
	musafi: ['musafi'],
	additional: ['musafi'],
	'additional value': ['musafi'],
	'additional number': ['musafi'],
	'mispar musafi': ['musafi'],
	'מספר מוספי': ['musafi'],
	מוספי: ['musafi'],
	atbash: ['atbash'],
	'at bash': ['atbash'],
	'אתב"ש': ['atbash'],
	'אתב״ש': ['atbash'],
	'את בש': ['atbash'],
	אתבש: ['atbash'],
	albam: ['albam'],
	'al bam': ['albam'],
	'אלב"ם': ['albam'],
	'אלב״ם': ['albam'],
	'אל בם': ['albam'],
	אלבם: ['albam'],
	boneeh: ['boneeh'],
	"bon'eh": ['boneeh'],
	"bone'eh": ['boneeh'],
	bonee: ['boneeh'],
	'building value': ['boneeh'],
	'mispar boneeh': ['boneeh'],
	'mispar bonee': ['boneeh'],
	"mispar bone'eh": ['boneeh'],
	'מספר בונה': ['boneeh'],
	בונה: ['boneeh'],
	kidmi: ['kidmi'],
	preceding: ['kidmi'],
	'preceding value': ['kidmi'],
	'preceding number': ['kidmi'],
	'mispar kidmi': ['kidmi'],
	'מספר קדמי': ['kidmi'],
	קדמי: ['kidmi'],
	'hamerubah haklali': ['hamerubah_haklali'],
	'general squared': ['hamerubah_haklali'],
	'general squared value': ['hamerubah_haklali'],
	'general squared number': ['hamerubah_haklali'],
	'squared value': ['hamerubah_haklali'],
	'squared number': ['hamerubah_haklali'],
	'mispar hamerubah haklali': ['hamerubah_haklali'],
	'מספר המרובע הכללי': ['hamerubah_haklali'],
	'המרובע הכללי': ['hamerubah_haklali'],
	meshulash: ['meshulash', 'kidmi', 'haachor'],
	triangular: ['meshulash', 'kidmi', 'haachor'],
	'triangular value': ['meshulash', 'kidmi', 'haachor'],
	'triangular number': ['meshulash', 'kidmi', 'haachor'],
	'mispar meshulash': ['meshulash', 'kidmi', 'haachor'],
	cubed: ['meshulash'],
	'cubed value': ['meshulash'],
	'מספר משולש': ['meshulash', 'kidmi', 'haachor'],
	משולש: ['meshulash', 'kidmi', 'haachor'],
	haachor: ['haachor'],
	achor: ['haachor'],
	backwards: ['haachor'],
	'backwards value': ['haachor'],
	'backwards number': ['haachor'],
	'mispar haachor': ['haachor'],
	'mispar achor': ['haachor'],
	"mispar ha'achor": ['haachor'],
	'מספר האחור': ['haachor'],
	האחור: ['haachor'],
	mispari: ['mispari'],
	counting: ['mispari'],
	'counting value': ['mispari'],
	'counting number': ['mispari'],
	'mispar mispari': ['mispari'],
	'מספר מספרי': ['mispari'],
	מספרי: ['mispari'],
	'katan mispari': ['katan_mispari'],
	'small counting': ['katan_mispari'],
	'small counting value': ['katan_mispari'],
	'small counting number': ['katan_mispari'],
	'mispar katan mispari': ['katan_mispari'],
	'mispar mispari katan': ['katan_mispari'],
	'מספר קטן מספרי': ['katan_mispari'],
	'קטן מספרי': ['katan_mispari'],
	kolel: ['kolel'],
	kollel: ['kolel'],
	addition: ['kolel'],
	'addition value': ['kolel'],
	'addition number': ['kolel'],
	'mispar kolel': ['kolel'],
	'מספר כלל': ['kolel'],
	כלל: ['kolel'],
	achbi: ['achbi'],
	'ach bi': ['achbi'],
	'אכב"י': ['achbi'],
	'אכב״י': ['achbi'],
	'אכ בי': ['achbi'],
	אכבי: ['achbi'],
	atbach: ['atbach'],
	'at bach': ['atbach'],
	'אטב"ח': ['atbach'],
	'אטב״ח': ['atbach'],
	'אט בח': ['atbach'],
	אטבח: ['atbach'],
	ayakbakar: ['ayakbakar'],
	ayakbachar: ['ayakbakar'],
	'ayak bakar': ['ayakbakar'],
	'ayak bachar': ['ayakbakar'],
	'ayak bakhar': ['ayakbakar'],
	'ayak bakkar': ['ayakbakar'],
	'אי"ק בכ"ר': ['ayakbakar'],
	'אי״ק בכ״ר': ['ayakbakar'],
	'איק בכר': ['ayakbakar'],
	איקבכר: ['ayakbakar'],
	ofanim: ['ofanim'],
	אופנים: ['ofanim'],
	achasbeta: ['achasbeta'],
	'achas beta': ['achasbeta'],
	'achas bata': ['achasbeta'],
	'אח"ס בט"ע': ['achasbeta'],
	'אח״ס בט״ע': ['achasbeta'],
	'אחס בטע': ['achasbeta'],
	אחסבטע: ['achasbeta'],
	avgad: ['avgad'],
	abgad: ['avgad'],
	'av gad': ['avgad'],
	'ab gad': ['avgad'],
	'אבג"ד': ['avgad'],
	'אבג״ד': ['avgad'],
	אבגד: ['avgad'],
	'אב גד': ['avgad'],
	'reverse avgad': ['reverse_avgad'],
	'reverse abgad': ['reverse_avgad'],
	'reverse av gad': ['reverse_avgad'],
	'reverse ab gad': ['reverse_avgad'],
	reverse: ['reverse_avgad'],
	'avgad reverse': ['reverse_avgad'],
	'abgad reverse': ['reverse_avgad'],
	'av gad reverse': ['reverse_avgad'],
	'ab gad reverse': ['reverse_avgad'],
	atba: ['reverse_avgad'],
	'at ba': ['reverse_avgad'],
	'אבג"ד הפוך': ['reverse_avgad'],
	'אבג״ד הפוך': ['reverse_avgad'],
	'אבגד הפוך': ['reverse_avgad'],
	'אב גד הפוך': ['reverse_avgad'],
	'אתב"א': ['reverse_avgad'],
	'אתב״א': ['reverse_avgad'],
	אתבא: ['reverse_avgad'],
	'את בא': ['reverse_avgad'],
};
