/** @type {Record<string, string[]>} */
export const holidays = {
	'rosh hashanah': ['rosh_hashanah'],
	'rosh hashana': ['rosh_hashanah'],
	'tzom gedaliah': ['tzom_gedaliah'],
	'tzom gedalya': ['tzom_gedaliah'],
	'yom kippur': ['yom_kippur'],
	'yom hakippurim': ['yom_kippur'],
	'sukkos': ['sukkos'],
	'sukkot': ['sukkos'],
	'succos': ['sukkos'],
	'succot': ['sukkos'],
	'shmini atzeres': ['shemini_atzeres'],
	'shemini atzeret': ['shemini_atzeres'],
	'simchas torah': ['simchas_torah'],
	'simchat torah': ['simchas_torah'],
	'rosh chodesh cheshvan': ['rosh_chodesh_cheshvan'],
	'sigd': ['sigd'],
	'rosh chodesh kislev': ['rosh_chodesh_kislev'],
	'chanukah': ['chanukah'],
	'channukah': ['chanukah'],
	'chanukkah': ['chanukah'],
	'channukkah': ['chanukah'],
	'chanuka': ['chanukah'],
	'chanukka': ['chanukah'],
	'channuka': ['chanukah'],
	'channukka': ['chanukah'],
	'hanukah': ['chanukah'],
	'hannukah': ['chanukah'],
	'hanukkah': ['chanukah'],
	'hannukkah': ['chanukah'],
	'hanuka': ['chanukah'],
	'hannuka': ['chanukah'],
	'hanukka': ['chanukah'],
	'hannukka': ['chanukah'],
	'rosh chodesh teves': ['rosh_chodesh_teves'],
	'rosh chodesh tevet': ['rosh_chodesh_teves'],
	"asara b'teves": ['asara_bteves'],
	'asarah b\'teves': ['asara_bteves'],
	'asarah bteves': ['asara_bteves'],
	'tenth of teves': ['asara_bteves'],
	'asara b\'tevet': ['asara_bteves'],
	'asarah b\'tevet': ['asara_bteves'],
	'asara btevet': ['asara_bteves'],
	'tenth of tevet': ['asara_bteves'],
	'rosh chodesh shevat': ['rosh_chodesh_shevat'],
	"tu b'shvat": ['tu_bshvat'],
	'tu bishvat': ['tu_bshvat'],
	'tu b\'shevat': ['tu_bshvat'],
	'tu beshvat': ['tu_bshvat'],
	'rosh chodesh adar i': ['rosh_chodesh_adar_i'],
	'rosh chodesh adar 1': ['rosh_chodesh_adar_i'],
	'rosh chodesh adar a': ['rosh_chodesh_adar_i'],
	'rosh chodesh adar ii': ['rosh_chodesh_adar_ii'],
	'rosh chodesh adar 2': ['rosh_chodesh_adar_ii'],
	'rosh chodesh adar b': ['rosh_chodesh_adar_ii'],
	'rosh chodesh adar': ['rosh_chodesh_adar'],
	"ta'anis esther": ['taanis_esther'],
	'taanis esther': ['taanis_esther'],
	"ta'anit esther": ['taanis_esther'],
	'taanit esther': ['taanis_esther'],
	'purim': ['purim'],
	'purrim': ['purim'],
	'shushan purim': ['shushan_purim'],
	'shushan purrim': ['shushan_purim'],
	'rosh chodesh nissan': ['rosh_chodesh_nissan'],
	'rosh chodesh nisan': ['rosh_chodesh_nissan'],
	'yom haaliyah': ['yom_haaliyah', 'yom_haaliyah_schools'],
	'yom ha\'aliyah': ['yom_haaliyah', 'yom_haaliyah_schools'],
	'yom haaliyah (observed in schools)': ['yom_haaliyah_schools'],
	'yom ha\'aliyah (observed in schools)': ['yom_haaliyah_schools'],
	"ta'anis bechoros": ['taanis_bechoros'],
	'taanis bechoros': ['taanis_bechoros'],
	"ta'anit bechorot": ['taanis_bechoros'],
	'taanit bechorot': ['taanis_bechoros'],
	'pesach': ['pesach'],
	'passover': ['pesach'],
	'yom hashoah': ['yom_hashoah'],
	'rosh chodesh iyar': ['rosh_chodesh_iyar'],
	'rosh chodesh iyyar': ['rosh_chodesh_iyar'],
	'yom hazikaron': ['yom_hazikaron'],
	"yom haatzma'ut": ['yom_haatzmaut'],
	"yom haatzma'us": ['yom_haatzmaut'],
	"yom haatzmaut": ['yom_haatzmaut'],
	"yom haatzmaus": ['yom_haatzmaut'],
	'pesach sheni': ['pesach_sheni'],
	"lag b'omer": ['lag_bomer'],
	'lag baomer': ['lag_bomer'],
	'yom yerushalayim': ['yom_yerushalayim'],
	'jerusalem day': ['yom_yerushalayim'],
	'rosh chodesh sivan': ['rosh_chodesh_sivan'],
	'shavuos': ['shavuos'],
	'shavuot': ['shavuos'],
	'rosh chodesh tammuz': ['rosh_chodesh_tammuz'],
	'rosh chodesh tamuz': ['rosh_chodesh_tammuz'],
	'tzom tammuz': ['tzom_tammuz'],
	'tzom tamuz': ['tzom_tammuz'],
	'seventeenth of tammuz': ['tzom_tammuz'],
	'seventeenth of tamuz': ['tzom_tammuz'],
	'17th of tammuz': ['tzom_tammuz'],
	'17th of tamuz': ['tzom_tammuz'],
	'rosh chodesh av': ['rosh_chodesh_av'],
	"tisha b'av": ['tisha_bav'],
	"tisha bav": ['tisha_bav'],
	'tishah b\'av': ['tisha_bav'],
	"tu b'av": ['tu_bav'],
	'tu bav': ['tu_bav'],
	'rosh chodesh elul': ['rosh_chodesh_elul'],
	'rosh chodesh ellul': ['rosh_chodesh_elul'],
	'shabbos mevorchim cheshvan': ['shabbos_mevorchim_cheshvan'],
	'shabbat mevorchim cheshvan': ['shabbos_mevorchim_cheshvan'],
	'shabbos mevorchim kislev': ['shabbos_mevorchim_kislev'],
	'shabbat mevorchim kislev': ['shabbos_mevorchim_kislev'],
	'shabbos mevorchim teves': ['shabbos_mevorchim_teves'],
	'shabbat mevorchim teves': ['shabbos_mevorchim_teves'],
	'shabbos mevorchim tevet': ['shabbos_mevorchim_shevat'],
	'shabbat mevorchim tevet': ['shabbos_mevorchim_shevat'],
	'shabbos mevorchim shevat': ['shabbos_mevorchim_shevat'],
	'shabbat mevorchim shevat': ['shabbos_mevorchim_shevat'],
	'shabbos mevorchim adar i': ['shabbos_mevorchim_adar_i'],
	'shabbat mevorchim adar i': ['shabbos_mevorchim_adar_i'],
	'shabbos mevorchim adar 1': ['shabbos_mevorchim_adar_i'],
	'shabbat mevorchim adar 1': ['shabbos_mevorchim_adar_i'],
	'shabbos mevorchim adar a': ['shabbos_mevorchim_adar_i'],
	'shabbat mevorchim adar a': ['shabbos_mevorchim_adar_i'],
	'shabbos mevorchim adar ii': ['shabbos_mevorchim_adar_ii'],
	'shabbat mevorchim adar ii': ['shabbos_mevorchim_adar_ii'],
	'shabbos mevorchim adar 2': ['shabbos_mevorchim_adar_ii'],
	'shabbat mevorchim adar 2': ['shabbos_mevorchim_adar_ii'],
	'shabbos mevorchim adar b': ['shabbos_mevorchim_adar_ii'],
	'shabbat mevorchim adar b': ['shabbos_mevorchim_adar_ii'],
	'shabbos mevorchim adar': ['shabbos_mevorchim_adar'],
	'shabbat mevorchim adar': ['shabbos_mevorchim_adar'],
	'shabbos mevorchim nissan': ['shabbos_mevorchim_nissan'],
	'shabbat mevorchim nissan': ['shabbos_mevorchim_nissan'],
	'shabbos mevorchim nisan': ['shabbos_mevorchim_nissan'],
	'shabbat mevorchim nisan': ['shabbos_mevorchim_nissan'],
	'shabbos mevorchim iyar': ['shabbos_mevorchim_iyar'],
	'shabbat mevorchim iyar': ['shabbos_mevorchim_iyar'],
	'shabbos mevorchim iyyar': ['shabbos_mevorchim_iyar'],
	'shabbat mevorchim iyyar': ['shabbos_mevorchim_iyar'],
	'shabbos mevorchim sivan': ['shabbos_mevorchim_sivan'],
	'shabbat mevorchim sivan': ['shabbos_mevorchim_sivan'],
	'shabbos mevorchim tammuz': ['shabbos_mevorchim_tammuz'],
	'shabbat mevorchim tammuz': ['shabbos_mevorchim_tammuz'],
	'shabbos mevorchim tamuz': ['shabbos_mevorchim_tammuz'],
	'shabbat mevorchim tamuz': ['shabbos_mevorchim_tammuz'],
	'shabbos mevorchim av': ['shabbos_mevorchim_av'],
	'shabbat mevorchim av': ['shabbos_mevorchim_av'],
	'shabbos mevorchim elul': ['shabbos_mevorchim_elul'],
	'shabbat mevorchim elul': ['shabbos_mevorchim_elul'],
	'shabbos mevorchim ellul': ['shabbos_mevorchim_elul'],
	'shabbat mevorchim ellul': ['shabbos_mevorchim_elul'],
	'shabbos shekalim': ['shabbos_shekalim'],
	'shabbat shekalim': ['shabbos_shekalim'],
	'shabbos zachor': ['shabbos_zachor'],
	'shabbat zachor': ['shabbos_zachor'],
	'shabbos parah': ['shabbos_parah'],
	'shabbat parah': ['shabbos_parah'],
	'shabbos hachodesh': ['shabbos_hachodesh'],
	'shabbat hachodesh': ['shabbos_hachodesh'],
	'shabbos hagadol': ['shabbos_hagadol'],
	'shabbat hagadol': ['shabbos_hagadol'],
	'shabbos chazon': ['shabbos_chazon'],
	'shabbat chazon': ['shabbos_chazon'],
	'shabbos nachamu': ['shabbos_nachamu'],
	'shabbat nachamu': ['shabbos_nachamu'],
	'shabbos shira': ['shabbos_shira'],
	'shabbat shira': ['shabbos_shira'],
	'shabbos shuva': ['shabbos_shuva'],
	'shabbat shuva': ['shabbos_shuva'],
	'leil selichos': ['leil_selichos'],
	'hoshanah rabbah': ['hoshanah_rabbah'],
	'hoshana rabba': ['hoshanah_rabbah'],
	'hoshanah rabah': ['hoshanah_rabbah'],
	'ben-gurion day': ['ben_gurion_day'],
	'ben gurion day': ['ben_gurion_day'],
	'rabin day': ['rabin_day'],
	'herzl day': ['herzl_day'],
	'jabotinsky day': ['jabotinsky_day'],
	'the rebbe recovers from illness': ['rebbe_recovers_from_illness'],
	'birthday and passing of rabbi dovber of lubavitch': ['birthday_and_passing_of_rabbi_dovber_of_lubavitch'],
	'liberation of rabbi dovber of lubavitch': ['liberation_of_rabbi_dovber_of_lubavitch'],
	'liberation of rabbi schneur zalman of liadi': ['liberation_of_rabbi_schneur_zalman_of_liadi'],
	'sefarim victory': ['sefarim_victory'],
	"yahrtzeit of rabbi yosef yitzchak schneersohn and beginning of rebbe's leadership": ['yahrtzeit_of_rabbi_yosef_yitzchak_schneersohn'],
	'passing of the rebbetzin chaya mushka schneerson': ['passing_of_rebbetzin_chaya_mushka_schneerson'],
	'birthday of the lubavitcher rebbe, rabbi menachem m. schneerson': ['birthday_of_lubavitcher_rebbe'],
	'birthday of rabbi shmuel of lubavitch': ['birthday_of_rabbi_shmuel_of_lubavitch'],
	'yahrtzeit of the lubavitcher rebbe, rabbi menachem m. schneerson': ['yahrtzeit_of_lubavitcher_rebbe'],
	'liberation of rabbi yosef yitzchak of lubavitch': ['liberation_of_rabbi_yosef_yitzchak_of_lubavitch'],
	'birthday of rabbi schneur zalman of liadi': ['birthday_of_rabbi_schneur_zalman_of_liadi'],
	'rosh chodesh': [
		'rosh_chodesh_nissan',
		'rosh_chodesh_iyar',
		'rosh_chodesh_sivan',
		'rosh_chodesh_tammuz',
		'rosh_chodesh_av',
		'rosh_chodesh_elul',
		'rosh_chodesh_tishrei',
		'rosh_chodesh_cheshvan',
		'rosh_chodesh_kislev',
		'rosh_chodesh_teves',
		'rosh_chodesh_shevat',
		'rosh_chodesh_adar',
		'rosh_chodesh_adar_i',
		'rosh_chodesh_adar_ii',
	],
};
