/** @type {Record<string, Record<string, string[]>>} */
export const units = {
	length: {
		'derech yom': ['derech_yom'],
		'mahalach yom': ['derech_yom'],
		'days walk': ['derech_yom'],
		"day's walk": ['derech_yom'],
		"days' walk": ['derech_yom'],
		parsah: ['parsah'],
		parsa: ['parsah'],
		parsahs: ['parsah'],
		parsaos: ['parsah'],
		parsaot: ['parsah'],
		parsas: ['parsah'],
		'persian miles': ['parsah'],
		mil: ['mil'],
		mill: ['mil'],
		milim: ['mil'],
		mils: ['mil'],
		milin: ['mil'],
		millin: ['mil'],
		ris: ['ris'],
		risim: ['ris'],
		risin: ['ris'],
		risses: ['ris'],
		rissim: ['ris'],
		riss: ['ris'],
		kaneh: ['kaneh'],
		kanehs: ['kaneh'],
		kane: ['kaneh'],
		reed: ['kaneh'],
		reeds: ['kaneh'],
		kanes: ['kaneh'],
		kanot: ['kaneh'],
		kanos: ['kaneh'],
		amah: ['amah'],
		amot: ['amah'],
		amos: ['amah'],
		amahs: ['amah'],
		cubit: ['amah'],
		cubits: ['amah'],
		'short amah': ['short_amah'],
		'short amot': ['short_amah'],
		'short amos': ['short_amah'],
		'short amahs': ['short_amah'],
		'amah bat chamishah': ['short_amah'],
		'amah bat chamesh': ['short_amah'],
		'amah bas chamishah': ['short_amah'],
		'amah bas chamesh': ['short_amah'],
		'amos bas chamishah': ['short_amah'],
		'amos bas chamesh': ['short_amah'],
		'amos bat chamishah': ['short_amah'],
		'amos bat chamesh': ['short_amah'],
		'short cubit': ['short_amah'],
		'short cubits': ['short_amah'],
		zeret: ['zeret'],
		zeretim: ['zeret'],
		zerets: ['zeret'],
		zeres: ['zeret'],
		zeresim: ['zeret'],
		tefach: ['tefach'],
		tefachim: ['tefach'],
		tefachs: ['tefach'],
		tefah: ['tefach'],
		handbreadth: ['tefach'],
		handbreadths: ['tefach'],
		etzba: ['etzbah'],
		etzbaos: ['etzbah'],
		etzbaot: ['etzbah'],
		etzbah: ['etzbah'],
		etzbahs: ['etzbah'],
		fingerbreadth: ['etzbah'],
		fingerbreadths: ['etzbah'],
		kilometer: ['kilometer'],
		kilometers: ['kilometer'],
		km: ['kilometer'],
		meter: ['meter'],
		meters: ['meter'],
		m: ['meter'],
		centimeter: ['centimeter'],
		centimeters: ['centimeter'],
		cm: ['centimeter'],
		millimeter: ['millimeter'],
		millimeters: ['millimeter'],
		mm: ['millimeter'],
		mile: ['mile'],
		miles: ['mile'],
		mi: ['mile'],
		yard: ['yard'],
		yards: ['yard'],
		yds: ['yard'],
		yd: ['yard'],
		foot: ['foot'],
		feet: ['foot'],
		ft: ['foot'],
		inch: ['inch'],
		inches: ['inch'],
		in: ['inch'],
		'nautical mile': ['nautical_mile'],
		'nautical miles': ['nautical_mile'],
		nautical: ['nautical_mile'],
		nmi: ['nautical_mile'],
	},
	area: {
		'beis kor': ['beis_kor'],
		'beit kor': ['beis_kor'],
		'bet kor': ['beis_kor'],
		'bait kor': ['beis_kor'],
		'bais kor': ['beis_kor'],
		'beis kors': ['beis_kor'],
		'beit kors': ['beis_kor'],
		'bet kors': ['beis_kor'],
		'bait kors': ['beis_kor'],
		'bais kors': ['beis_kor'],
		'batei kor': ['beis_kor'],
		'beit korim': ['beis_kor'],
		'beis seasayim': ['beis_seasayim'],
		'beit seatayim': ['beis_seasayim'],
		'bet seatayim': ['beis_seasayim'],
		'bait seatayim': ['beis_seasayim'],
		'bais seasayim': ['beis_seasayim'],
		'beis seasayims': ['beis_seasayim'],
		'beit seatayims': ['beis_seasayim'],
		'bet seatayims': ['beis_seasayim'],
		'bait seatayims': ['beis_seasayim'],
		'bais seasayims': ['beis_seasayim'],
		'batei seatayim': ['beis_seasayim'],
		'batei seasayim': ['beis_seasayim'],
		'beit seatayimim': ['beis_seasayim'],
		'beis seah': ['beis_seah'],
		'beit seah': ['beis_seah'],
		'bet seah': ['beis_seah'],
		'bait seah': ['beis_seah'],
		'bais seah': ['beis_seah'],
		'beis seahs': ['beis_seah'],
		'beit seahs': ['beis_seah'],
		'bet seahs': ['beis_seah'],
		'bait seahs': ['beis_seah'],
		'bais seahs': ['beis_seah'],
		'batei seah': ['beis_seah'],
		'beit seos': ['beis_seah'],
		'beis kav': ['beis_kav'],
		'beit kav': ['beis_kav'],
		'bet kav': ['beis_kav'],
		'bait kav': ['beis_kav'],
		'bais kav': ['beis_kav'],
		'beis kavs': ['beis_kav'],
		'beit kavs': ['beis_kav'],
		'bet kavs': ['beis_kav'],
		'bait kavs': ['beis_kav'],
		'bais kavs': ['beis_kav'],
		'batei kav': ['beis_kav'],
		'beit kavim': ['beis_kav'],
		'beis rova': ['beis_rova'],
		'beit rova': ['beis_rova'],
		'bet rova': ['beis_rova'],
		'bait rova': ['beis_rova'],
		'bais rova': ['beis_rova'],
		'beis rovas': ['beis_rova'],
		'beit rovas': ['beis_rova'],
		'bet rovas': ['beis_rova'],
		'bait rovas': ['beis_rova'],
		'bais rovas': ['beis_rova'],
		'batei rova': ['beis_rova'],
		'beit rovaim': ['beis_rova'],
		'amah merubaas': ['amah_merubaas'],
		'amah merubas': ['amah_merubaas'],
		'amah merubaat': ['amah_merubaas'],
		'amah merubat': ['amah_merubaas'],
		'amah merubah': ['amah_merubaas'],
		'amah meruba': ['amah_merubaas'],
		'amah merubahs': ['amah_merubaas'],
		'amot merubaas': ['amah_merubaas'],
		'amot merubaat': ['amah_merubaas'],
		'amos merubaas': ['amah_merubaas'],
		'amot merubah': ['amah_merubaas'],
		'amos merubah': ['amah_merubaas'],
		'square amos': ['amah_merubaas'],
		'square amot': ['amah_merubaas'],
		'square amahs': ['amah_merubaas'],
		'square amah': ['amah_merubaas'],
		'square cubits': ['amah_merubaas'],
		'square cubit': ['amah_merubaas'],
		'amah al amah': ['amah_merubaas'],
		'amah al amahs': ['amah_merubaas'],
		'amot al amot': ['amah_merubaas'],
		'amos al amos': ['amah_merubaas'],
		'tefach merubaas': ['tefach_merubah'],
		'tefach merubas': ['tefach_merubah'],
		'tefach merubaat': ['tefach_merubah'],
		'tefach merubat': ['tefach_merubah'],
		'tefach merubah': ['tefach_merubah'],
		'tefach meruba': ['tefach_merubah'],
		'tefach merubahs': ['tefach_merubah'],
		'tefachim merubaat': ['tefach_merubah'],
		'tefachim merubaas': ['tefach_merubah'],
		'tefachim merubah': ['tefach_merubah'],
		'square tefachim': ['tefach_merubah'],
		'square tefachs': ['tefach_merubah'],
		'square tefach': ['tefach_merubah'],
		'square handbreadths': ['tefach_merubah'],
		'square handbreadth': ['tefach_merubah'],
		'tefach al tefach': ['tefach_merubah'],
		'tefach al tefachs': ['tefach_merubah'],
		'tefachim al tefachim': ['tefach_merubah'],
		'etzbah merubaas': ['etzbah_merubaas'],
		'etzbah merubas': ['etzbah_merubaas'],
		'etzbah merubaat': ['etzbah_merubaas'],
		'etzbah merubat': ['etzbah_merubaas'],
		'etzbah merubah': ['etzbah_merubaas'],
		'etzbah meruba': ['etzbah_merubaas'],
		'etzbah merubahs': ['etzbah_merubaas'],
		'etzba merubaas': ['etzbah_merubaas'],
		'etzba merubas': ['etzbah_merubaas'],
		'etzba merubaat': ['etzbah_merubaas'],
		'etzba merubat': ['etzbah_merubaas'],
		'etzba merubah': ['etzbah_merubaas'],
		'etzba meruba': ['etzbah_merubaas'],
		'etzba merubahs': ['etzbah_merubaas'],
		'etzbaos merubaat': ['etzbah_merubaas'],
		'etzbaos merubaas': ['etzbah_merubaas'],
		'etzbaos merubah': ['etzbah_merubaas'],
		'square etzbaos': ['etzbah_merubaas'],
		'square etzbaot': ['etzbah_merubaas'],
		'square etzbahs': ['etzbah_merubaas'],
		'square etzbah': ['etzbah_merubaas'],
		'square etzba': ['etzbah_merubaas'],
		'square fingerbreadths': ['etzbah_merubaas'],
		'square fingerbreadth': ['etzbah_merubaas'],
		'etzba al etzba': ['etzbah_merubaas'],
		'etzbah al etzbah': ['etzbah_merubaas'],
		'etzbaos al etzbaos': ['etzbah_merubaas'],
		'etzbaot al etzbaot': ['etzbah_merubaas'],
		gris: ['gris'],
		grises: ['gris'],
		griss: ['gris'],
		grissim: ['gris'],
		grissin: ['gris'],
		grisim: ['gris'],
		grisin: ['gris'],
		bean: ['gris'],
		beans: ['gris'],
		'bean area': ['gris'],
		'bean areas': ['gris'],
		'split bean': ['gris'],
		'split beans': ['gris'],
		'split bean area': ['gris'],
		'split bean areas': ['gris'],
		grisos: ['gris'],
		grisot: ['gris'],
		grisoth: ['gris'],
		adashah: ['adashah'],
		adasha: ['adashah'],
		adashot: ['adashah'],
		adashos: ['adashah'],
		addashah: ['adashah'],
		lentil: ['adashah'],
		lentils: ['adashah'],
		'lentil area': ['adashah'],
		'lentil areas': ['adashah'],
		searah: ['searah'],
		searos: ['searah'],
		searim: ['searah'],
		sear: ['searah'],
		shear: ['searah'],
		shaar: ['searah'],
		'searah area': ['searah'],
		'searah areas': ['searah'],
		hairbreadth: ['searah'],
		hairbreadths: ['searah'],
		hair: ['searah'],
		hairs: ['searah'],
		'square kilometer': ['square_kilometer'],
		'square kilometers': ['square_kilometer'],
		'square km': ['square_kilometer'],
		'sq km': ['square_kilometer'],
		'sq. km': ['square_kilometer'],
		'sq km.': ['square_kilometer'],
		'sq. km.': ['square_kilometer'],
		'km^2': ['square_kilometer'],
		'square meter': ['square_meter'],
		'square meters': ['square_meter'],
		'square m': ['square_meter'],
		'sq m': ['square_meter'],
		'sq. m': ['square_meter'],
		'sq m.': ['square_meter'],
		'sq. m.': ['square_meter'],
		'm^2': ['square_meter'],
		'square centimeter': ['square_centimeter'],
		'square centimeters': ['square_centimeter'],
		'square cm': ['square_centimeter'],
		'sq cm': ['square_centimeter'],
		'sq. cm': ['square_centimeter'],
		'sq cm.': ['square_centimeter'],
		'sq. cm.': ['square_centimeter'],
		'cm^2': ['square_centimeter'],
		'square mile': ['square_mile'],
		'square miles': ['square_mile'],
		'square mi': ['square_mile'],
		'sq mi': ['square_mile'],
		'sq. mi': ['square_mile'],
		'sq mi.': ['square_mile'],
		'sq. mi.': ['square_mile'],
		'mi^2': ['square_mile'],
		'square yard': ['square_yard'],
		'square yards': ['square_yard'],
		'square yd': ['square_yard'],
		'sq yd': ['square_yard'],
		'sq. yd': ['square_yard'],
		'sq yd.': ['square_yard'],
		'sq. yd.': ['square_yard'],
		'yd^2': ['square_yard'],
		'square foot': ['square_foot'],
		'square feet': ['square_foot'],
		'square ft': ['square_foot'],
		'sq ft': ['square_foot'],
		'sq. ft': ['square_foot'],
		'sq ft.': ['square_foot'],
		'sq. ft.': ['square_foot'],
		'ft^2': ['square_foot'],
		'square inch': ['square_inch'],
		'square inches': ['square_inch'],
		'square in': ['square_inch'],
		'sq in': ['square_inch'],
		'sq. in': ['square_inch'],
		'sq in.': ['square_inch'],
		'sq. in.': ['square_inch'],
		'in^2': ['square_inch'],
		hectare: ['hectare'],
		hectares: ['hectare'],
		ha: ['hectare'],
		acre: ['acre'],
		acres: ['acre'],
		ac: ['acre'],
	},
	volume: {
		kor: ['kor'],
		kors: ['kor'],
		korim: ['kor'],
		chomer: ['kor'],
		chomers: ['kor'],
		chomerim: ['kor'],
		letech: ['letech'],
		letechs: ['letech'],
		letechim: ['letech'],
		adriv: ['letech'],
		adrivs: ['letech'],
		adrivim: ['letech'],
		ephah: ['ephah'],
		ephos: ['ephah'],
		ephot: ['ephah'],
		ephahs: ['ephah'],
		bat: ['ephah'],
		bats: ['ephah'],
		batim: ['ephah'],
		bas: ['ephah'],
		basim: ['ephah'],
		seah: ['seah'],
		seahs: ['seah'],
		seos: ['seah'],
		seot: ['seah'],
		tarkav: ['tarkav'],
		tarkavs: ['tarkav'],
		tarkavim: ['tarkav'],
		hin: ['tarkav'],
		hins: ['tarkav'],
		hinim: ['tarkav'],
		issaron: ['issaron'],
		issarons: ['issaron'],
		issaronim: ['issaron'],
		omer: ['issaron'],
		omers: ['issaron'],
		omerim: ['issaron'],
		kav: ['kav'],
		kavs: ['kav'],
		kavim: ['kav'],
		rova: ['rova'],
		rovas: ['rova'],
		rovos: ['rova'],
		rovot: ['rova'],
		rovah: ['rova'],
		rovahs: ['rova'],
		rovim: ['rova'],
		log: ['rova'],
		logs: ['rova'],
		logim: ['rova'],
		lug: ['rova'],
		lugs: ['rova'],
		lugim: ['rova'],
		tomen: ['tomen'],
		tomens: ['tomen'],
		tomenim: ['tomen'],
		reviis: ['reviis'],
		revis: ['reviis'],
		'quarter log': ['reviis'],
		cheekful: ['reviis'],
		cheekfuls: ['reviis'],
		reviisos: ['reviis'],
		reviit: ['reviis'],
		revit: ['reviis'],
		reviitot: ['reviis'],
		reviisim: ['reviis'],
		uchlah: ['uchlah'],
		uchla: ['uchlah'],
		uchlahs: ['uchlah'],
		uchlos: ['uchlah'],
		uchlot: ['uchlah'],
		uchlas: ['uchlah'],
		klah: ['uchlah'],
		kla: ['uchlah'],
		klahs: ['uchlah'],
		kalos: ['uchlah'],
		kalot: ['uchlah'],
		klas: ['uchlah'],
		beitzah: ['beitzah'],
		beitzim: ['beitzah'],
		betzah: ['beitzah'],
		beitzahs: ['beitzah'],
		egg: ['beitzah'],
		eggs: ['beitzah'],
		kezayis: ['kezayis'],
		kezayit: ['kezayis'],
		kezayises: ['kezayis'],
		kezaysim: ['kezayis'],
		kezaytim: ['kezayis'],
		kezayisim: ['kezayis'],
		kezayitim: ['kezayis'],
		olive: ['kezayis'],
		olives: ['kezayis'],
		'olive bulk': ['kezayis'],
		'olive bulks': ['kezayis'],
		grogeres: ['grogeres'],
		grogeret: ['grogeres'],
		grogaros: ['grogeres'],
		grogarot: ['grogeres'],
		fig: ['grogeres'],
		figs: ['grogeres'],
		mesurah: ['mesurah'],
		mesura: ['mesurah'],
		mesuros: ['mesurah'],
		mesurot: ['mesurah'],
		mesuras: ['mesurah'],
		mesurahs: ['mesurah'],
		kortov: ['kortov'],
		kortovs: ['kortov'],
		kortovim: ['kortov'],
		gallon: ['us_liquid_gallon'],
		'us gallon': ['us_liquid_gallon'],
		'us liquid gallon': ['us_liquid_gallon'],
		'liquid gallon': ['us_liquid_gallon'],
		gallons: ['us_liquid_gallon'],
		'us gallons': ['us_liquid_gallon'],
		'us liquid gallons': ['us_liquid_gallon'],
		'liquid gallons': ['us_liquid_gallon'],
		quart: ['us_liquid_quart'],
		'us quart': ['us_liquid_quart'],
		'us liquid quart': ['us_liquid_quart'],
		'liquid quart': ['us_liquid_quart'],
		quarts: ['us_liquid_quart'],
		'us quarts': ['us_liquid_quart'],
		'us liquid quarts': ['us_liquid_quart'],
		'liquid quarts': ['us_liquid_quart'],
		pint: ['us_liquid_pint'],
		'us pint': ['us_liquid_pint'],
		'us liquid pint': ['us_liquid_pint'],
		'liquid pint': ['us_liquid_pint'],
		pints: ['us_liquid_pint'],
		'us pints': ['us_liquid_pint'],
		'us liquid pints': ['us_liquid_pint'],
		'liquid pints': ['us_liquid_pint'],
		cup: ['us_cup'],
		'us cup': ['us_cup'],
		'us liquid cup': ['us_cup'],
		'liquid cup': ['us_cup'],
		cups: ['us_cup'],
		'us cups': ['us_cup'],
		'us liquid cups': ['us_cup'],
		'liquid cups': ['us_cup'],
		'fluid ounce': ['us_fluid_ounce'],
		'us fluid ounce': ['us_fluid_ounce'],
		'fluid ounces': ['us_fluid_ounce'],
		'us fluid ounces': ['us_fluid_ounce'],
		'fluid oz': ['us_fluid_ounce'],
		'us fluid oz': ['us_fluid_ounce'],
		'fl oz': ['us_fluid_ounce'],
		'us fl. oz': ['us_fluid_ounce'],
		tablespoon: ['us_tablespoon'],
		tbsp: ['us_tablespoon'],
		'tbsp.': ['us_tablespoon'],
		'tb. sp': ['us_tablespoon'],
		'us tablespoon': ['us_tablespoon'],
		'us tbsp': ['us_tablespoon'],
		tablespoons: ['us_tablespoon'],
		tbsps: ['us_tablespoon'],
		'us tablespoons': ['us_tablespoon'],
		'us tbsps': ['us_tablespoon'],
		teaspoon: ['us_teaspoon'],
		tsp: ['us_teaspoon'],
		'tsp.': ['us_teaspoon'],
		'us teaspoon': ['us_teaspoon'],
		'us tsp': ['us_teaspoon'],
		teaspoons: ['us_teaspoon'],
		tsps: ['us_teaspoon'],
		'us teaspoons': ['us_teaspoon'],
		'us tsps': ['us_teaspoon'],
		'cubic meter': ['cubic_meter'],
		'cubic meters': ['cubic_meter'],
		'cubic m': ['cubic_meter'],
		'cube meter': ['cubic_meter'],
		'cube meters': ['cubic_meter'],
		'cube m': ['cubic_meter'],
		'cu m': ['cubic_meter'],
		'cu meters': ['cubic_meter'],
		'cu. m': ['cubic_meter'],
		'cu. meters': ['cubic_meter'],
		'm^3': ['cubic_meter'],
		'cubic centimeter': ['cubic_centimeter'],
		'cubic centimeters': ['cubic_centimeter'],
		'cubic cm': ['cubic_centimeter'],
		'cube centimeter': ['cubic_centimeter'],
		'cube centimeters': ['cubic_centimeter'],
		'cube cm': ['cubic_centimeter'],
		'cu cm': ['cubic_centimeter'],
		'cu centimeters': ['cubic_centimeter'],
		'cu. cm': ['cubic_centimeter'],
		'cu. centimeters': ['cubic_centimeter'],
		'cm^3': ['cubic_centimeter'],
		liters: ['liter'],
		liter: ['liter'],
		l: ['liter'],
		ltr: ['liter'],
		ml: ['milliliter'],
		milliliter: ['milliliter'],
		milliliters: ['milliliter'],
		mltr: ['milliliter'],
		'imp gallon': ['imperial_gallon'],
		'imperial gallon': ['imperial_gallon'],
		'imperial liquid gallon': ['imperial_gallon'],
		'imp liquid gallon': ['imperial_gallon'],
		'imp gallons': ['imperial_gallon'],
		'imperial gallons': ['imperial_gallon'],
		'imperial liquid gallons': ['imperial_gallon'],
		'imp liquid gallons': ['imperial_gallon'],
		'imp quart': ['imperial_quart'],
		'imperial quart': ['imperial_quart'],
		'imperial liquid quart': ['imperial_quart'],
		'imp liquid quart': ['imperial_quart'],
		'imp quarts': ['imperial_quart'],
		'imperial quarts': ['imperial_quart'],
		'imperial liquid quarts': ['imperial_quart'],
		'imp liquid quarts': ['imperial_quart'],
		'imp pint': ['imperial_pint'],
		'imperial pint': ['imperial_pint'],
		'imperial liquid pint': ['imperial_pint'],
		'imp liquid pint': ['imperial_pint'],
		'imp pints': ['imperial_pint'],
		'imperial pints': ['imperial_pint'],
		'imperial liquid pints': ['imperial_pint'],
		'imp liquid pints': ['imperial_pint'],
		'imp cup': ['imperial_cup'],
		'imperial cup': ['imperial_cup'],
		'imperial liquid cup': ['imperial_cup'],
		'imp liquid cup': ['imperial_cup'],
		'imp cups': ['imperial_cup'],
		'imperial cups': ['imperial_cup'],
		'imperial liquid cups': ['imperial_cup'],
		'imp liquid cups': ['imperial_cup'],
		'imp tablespoon': ['imperial_tablespoon'],
		'imp tbsp': ['imperial_tablespoon'],
		'imp tb. sp': ['imperial_tablespoon'],
		'imperial tablespoon': ['imperial_tablespoon'],
		'imperial tbsp': ['imperial_tablespoon'],
		'imp tablespoons': ['imperial_tablespoon'],
		'imp tbsps': ['imperial_tablespoon'],
		'imperial tablespoons': ['imperial_tablespoon'],
		'imperial tbsps': ['imperial_tablespoon'],
		'imp teaspoon': ['imperial_teaspoon'],
		'imp tsp': ['imperial_teaspoon'],
		'imp tb. sp.': ['imperial_teaspoon'],
		'imperial teaspoon': ['imperial_teaspoon'],
		'imperial tsp': ['imperial_teaspoon'],
		'imp teaspoons': ['imperial_teaspoon'],
		'imp tsps': ['imperial_teaspoon'],
		'imperial teaspoons': ['imperial_teaspoon'],
		'imperial tsps': ['imperial_teaspoon'],
		'cubic foot': ['cubic_foot'],
		'cubic feet': ['cubic_foot'],
		'cubic ft': ['cubic_foot'],
		'cube foot': ['cubic_foot'],
		'cu feet': ['cubic_foot'],
		'cu. ft': ['cubic_foot'],
		'cu foot': ['cubic_foot'],
		'cu. foot': ['cubic_foot'],
		'cu. feet': ['cubic_foot'],
		'cu ft': ['cubic_foot'],
		'cu ft.': ['cubic_foot'],
		'cu. ft.': ['cubic_foot'],
		'ft^3': ['cubic_foot'],
		'cubic inch': ['cubic_inch'],
		'cubic inches': ['cubic_inch'],
		'cubic in': ['cubic_inch'],
		'cube inch': ['cubic_inch'],
		'cu inch': ['cubic_inch'],
		'cu. in': ['cubic_inch'],
		'cu in': ['cubic_inch'],
		'cu. inch': ['cubic_inch'],
		'cu inches': ['cubic_inch'],
		'cu. inches': ['cubic_inch'],
		'cu in.': ['cubic_inch'],
		'cu. in.': ['cubic_inch'],
		'in^3': ['cubic_inch'],
	},
	weight: {
		'kikar weight': ['kikar'],
		kikar: ['kikar'],
		kikars: ['kikar'],
		kikarim: ['kikar'],
		mane: ['mane'],
		manes: ['mane'],
		manos: ['mane'],
		manot: ['mane'],
		manehs: ['mane'],
		litra: ['mane'],
		litras: ['mane'],
		litrot: ['mane'],
		litros: ['mane'],
		tartimar: ['tartimar'],
		tartimars: ['tartimar'],
		tartimarim: ['tartimar'],
		unkeya: ['unkeya'],
		unkeyah: ['unkeya'],
		unkeyas: ['unkeya'],
		unkeyos: ['unkeya'],
		unkeyot: ['unkeya'],
		unkiyah: ['unkeya'],
		unkiyas: ['unkeya'],
		sela: ['sela'],
		selayim: ['sela'],
		selas: ['sela'],
		selah: ['sela'],
		selahs: ['sela'],
		sla: ['sela'],
		shekel: ['shekel'],
		shekalim: ['shekel'],
		shkalim: ['shekel'],
		shekels: ['shekel'],
		'old shekel': ['shekel'],
		'old sheqel': ['shekel'],
		'old shekels': ['shekel'],
		'old sheqels': ['shekel'],
		'ancient shekel': ['shekel'],
		'ancient sheqel': ['shekel'],
		'ancient shekels': ['shekel'],
		'ancient sheqels': ['shekel'],
		dinar: ['dinar'],
		zuz: ['dinar'],
		zin: ['dinar'],
		dinarim: ['dinar'],
		zuzim: ['dinar'],
		zinim: ['dinar'],
		dinars: ['dinar'],
		zuzes: ['dinar'],
		zins: ['dinar'],
		dinarin: ['dinar'],
		zuzin: ['dinar'],
		zinin: ['dinar'],
		kilograms: ['kilogram'],
		kilogram: ['kilogram'],
		kg: ['kilogram'],
		gram: ['gram'],
		grams: ['gram'],
		g: ['gram'],
		gm: ['gram'],
		milligrams: ['milligram'],
		milligram: ['milligram'],
		mg: ['milligram'],
		stone: ['stone'],
		stones: ['stone'],
		st: ['stone'],
		pound: ['pound'],
		pounds: ['pound'],
		lb: ['pound'],
		lbs: ['pound'],
		ounces: ['ounce'],
		ounce: ['ounce'],
		oz: ['ounce'],
	},
	coins: {
		'kikar kodesh': ['kikar_shel_kodesh'],
		'kikar shel kodesh': ['kikar_shel_kodesh'],
		'kikars shel kodesh': ['kikar_shel_kodesh'],
		'kikarim shel kodesh': ['kikar_shel_kodesh'],
		'kikar shel kodeshes': ['kikar_shel_kodesh'],
		'kikar coin': ['kikar'],
		'kikar money': ['kikar'],
		kikar: ['kikar'],
		kikars: ['kikar'],
		kikarim: ['kikar'],
		'mane shel kodesh': ['mane_shel_kodesh'],
		'mane kodesh': ['mane_shel_kodesh'],
		'maneh shel kodesh': ['mane_shel_kodesh'],
		'maneh kodesh': ['mane_shel_kodesh'],
		'manehs shel kodesh': ['mane_shel_kodesh'],
		'manos shel kodesh': ['mane_shel_kodesh'],
		'manot shel kodesh': ['mane_shel_kodesh'],
		'maneh shel kodeshes': ['mane_shel_kodesh'],
		'maneh coin': ['mane'],
		'maneh money': ['mane'],
		mane: ['mane'],
		manehs: ['mane'],
		maneh: ['mane'],
		manos: ['mane'],
		manot: ['mane'],
		'dinar zahav': ['dinar_zahav'],
		'dinarim zahav': ['dinar_zahav'],
		'gold dinar': ['dinar_zahav'],
		'gold dinars': ['dinar_zahav'],
		'gold dinarim': ['dinar_zahav'],
		'dinarim shel zahav': ['dinar_zahav'],
		'dinar shel zahav': ['dinar_zahav'],
		'sela coin': ['sela'],
		'sela money': ['sela'],
		sela: ['sela'],
		selas: ['sela'],
		selayim: ['sela'],
		selah: ['sela'],
		selahs: ['sela'],
		sla: ['sela'],
		'shekel coin': ['shekel', 'nis'],
		'shekel money': ['shekel', 'nis'],
		shekel: ['shekel', 'nis'],
		shekalim: ['shekel', 'nis'],
		shkalim: ['shekel', 'nis'],
		shekels: ['shekel', 'nis'],
		sheqel: ['shekel', 'nis'],
		sheqels: ['shekel', 'nis'],
		'old shekel': ['shekel'],
		'old sheqel': ['shekel'],
		'old shekels': ['shekel'],
		'old sheqels': ['shekel'],
		'ancient shekel': ['shekel'],
		'ancient sheqel': ['shekel'],
		'ancient shekels': ['shekel'],
		'ancient sheqels': ['shekel'],
		'dinar coin': ['dinar'],
		'zuz coin': ['dinar'],
		'dinar money': ['dinar'],
		'zuz money': ['dinar'],
		dinar: ['dinar'],
		zuz: ['dinar'],
		dinarim: ['dinar'],
		zuzim: ['dinar'],
		dinars: ['dinar'],
		zuzes: ['dinar'],
		dinarin: ['dinar'],
		zuzin: ['dinar'],
		'istera coin': ['istera'],
		'istera money': ['istera'],
		istera: ['istera'],
		isteras: ['istera'],
		isteros: ['istera'],
		isterot: ['istera'],
		'isterah coin': ['istera'],
		'isterah money': ['istera'],
		isterah: ['istera'],
		'tarpik coin': ['istera'],
		'tarpik money': ['istera'],
		tarpik: ['istera'],
		tarpiks: ['istera'],
		tarpikim: ['istera'],
		'maah coin': ['maah'],
		'maah money': ['maah'],
		maah: ['maah'],
		maos: ['maah'],
		maot: ['maah'],
		maa: ['maah'],
		maas: ['maah'],
		maahs: ['maah'],
		pundyon: ['pundyon'],
		pundyonim: ['pundyon'],
		pundyons: ['pundyon'],
		'issar coin': ['issar'],
		'issar money': ['issar'],
		issar: ['issar'],
		issars: ['issar'],
		issarim: ['issar'],
		isser: ['issar'],
		isserim: ['issar'],
		issers: ['issar'],
		'mesimas coin': ['mesimas'],
		'mesimas money': ['mesimas'],
		mesimas: ['mesimas'],
		mesima: ['mesimas'],
		mesimos: ['mesimas'],
		mesimot: ['mesimas'],
		mesimah: ['mesimas'],
		messimas: ['mesimas'],
		'kontrank coin': ['kontrank'],
		'kontrank money': ['kontrank'],
		kontrank: ['kontrank'],
		kontranks: ['kontrank'],
		kontrankim: ['kontrank'],
		kontronk: ['kontrank'],
		kontronks: ['kontrank'],
		kontronkim: ['kontrank'],
		'perutah coin': ['perutah'],
		'perutah money': ['perutah'],
		perutah: ['perutah'],
		perutahs: ['perutah'],
		perutos: ['perutah'],
		perutot: ['perutah'],
		'prutah coin': ['perutah'],
		'prutah money': ['perutah'],
		prutah: ['perutah'],
		prutos: ['perutah'],
		prutot: ['perutah'],
		pruta: ['perutah'],
		prutahs: ['perutah'],
		prutas: ['perutah'],
		usd: ['usd'],
		'us dollars': ['usd'],
		'us dollar': ['usd'],
		'us dollars (usd)': ['usd'],
		'us dollar (usd)': ['usd'],
		dollar: ['usd'],
		dollars: ['usd'],
		'dollar (usd)': ['usd'],
		'dollars (usd)': ['usd'],
		nis: ['nis'],
		ils: ['nis'],
		'israeli new sheqel': ['nis'],
		'israeli new sheqels': ['nis'],
		'israeli new shekel': ['nis'],
		'israeli new shekels': ['nis'],
		'israeli new sheqel (nis)': ['nis'],
		'israeli new sheqels (nis)': ['nis'],
		eur: ['eur'],
		euro: ['eur'],
		euros: ['eur'],
		'european euro': ['eur'],
		'european euros': ['eur'],
		'european euro (eur)': ['eur'],
		'european euros (eur)': ['eur'],
		cad: ['cad'],
		'canadian dollar': ['cad'],
		'canadian dollars': ['cad'],
		'canadian dollar (cad)': ['cad'],
		'canadian dollars (cad)': ['cad'],
		gbp: ['gbp'],
		'pound sterling': ['gbp'],
		'pounds sterling': ['gbp'],
		'pound sterling (gbp)': ['gbp'],
		'pounds sterling (gbp)': ['gbp'],
		'british pound': ['gbp'],
		'british pounds': ['gbp'],
		pound: ['gbp'],
		pounds: ['gbp'],
		'gram of silver': ['grams_of_silver'],
		'grams of silver': ['grams_of_silver'],
		'g of silver': ['grams_of_silver'],
		'gm of silver': ['grams_of_silver'],
		'ounce of silver': ['ounces_of_silver'],
		'ounces of silver': ['ounces_of_silver'],
		'oz of silver': ['ounces_of_silver'],
		'troy ounce of silver': ['ounces_of_silver'],
		'troy ounces of silver': ['ounces_of_silver'],
		'troy oz of silver': ['ounces_of_silver'],
		'troy ounce': ['ounces_of_silver'],
		'troy ounces': ['ounces_of_silver'],
		'troy oz': ['ounces_of_silver'],
	},
	time: {
		yovel: ['yovel'],
		yovelos: ['yovel'],
		yovels: ['yovel'],
		yovelot: ['yovel'],
		jubilee: ['yovel'],
		jubilees: ['yovel'],
		shmittah: ['shmittah'],
		shemittahs: ['shmittah'],
		shmitta: ['shmittah'],
		shmittas: ['shmittah'],
		shmittos: ['shmittah'],
		shmittot: ['shmittah'],
		sabbatical: ['shmittah'],
		sabbaticals: ['shmittah'],
		shemita: ['shmittah'],
		shemitas: ['shmittah'],
		shana: ['shanah'],
		shanahs: ['shanah'],
		shanim: ['shanah'],
		'hebrew years': ['shanah'],
		'jewish years': ['shanah'],
		shanah: ['shanah'],
		'hebrew year': ['shanah'],
		'jewish year': ['shanah'],
		tekufah: ['tekufah'],
		tekufos: ['tekufah'],
		tekufot: ['tekufah'],
		tekufas: ['tekufah'],
		tekufahs: ['tekufah'],
		tekufa: ['tekufah'],
		chodesh: ['chodesh'],
		chodashim: ['chodesh'],
		chodashot: ['chodesh'],
		chodashos: ['chodesh'],
		chodeshes: ['chodesh'],
		'hebrew months': ['chodesh'],
		'jewish months': ['chodesh'],
		molad: ['molad'],
		'molad emtzai': ['molad'],
		'molad emtzaiim': ['molad'],
		'molad emtzaim': ['molad'],
		'molad interval': ['molad'],
		molads: ['molad'],
		moladot: ['molad'],
		molados: ['molad'],
		'molad intervals': ['molad'],
		shavuah: ['shavuah'],
		shavua: ['shavuah'],
		shvua: ['shavuah'],
		shvuah: ['shavuah'],
		shavuos: ['shavuah'],
		shvuos: ['shavuah'],
		shavuot: ['shavuah'],
		shvuot: ['shavuah'],
		yom: ['yom'],
		yam: ['yom'],
		'hebrew days': ['yom'],
		'hebrew day': ['yom'],
		yamim: ['yom'],
		yomim: ['yom'],
		onah: ['onah'],
		onaah: ['onah'],
		onos: ['onah'],
		onot: ['onah'],
		ona: ['onah'],
		onahs: ['onah'],
		'large onah': ['onah'],
		'onah gadol': ['onah'],
		'onah gadols': ['onah'],
		'large onos': ['onah'],
		'large onot': ['onah'],
		'large onahs': ['onah'],
		'large onaah': ['onah'],
		shaah: ['shaah'],
		'shaah regilah': ['shaah'],
		'hebrew hour': ['shaah'],
		shaot: ['shaah'],
		shaos: ['shaah'],
		shaahs: ['shaah'],
		'hiluch mil': ['hiluch_mil'],
		'hiluch mils': ['hiluch_mil'],
		'hiluch milim': ['hiluch_mil'],
		'hiluchei mil': ['hiluch_mil'],
		'hiluchei milim': ['hiluch_mil'],
		'hiluch milin': ['hiluch_mil'],
		'kdei achilas peras': ['kdei_achilas_pras'],
		"k'dei achilas peras": ['kdei_achilas_pras'],
		'kdei achilas pras': ['kdei_achilas_pras'],
		"k'dei achilas pras": ['kdei_achilas_pras'],
		'kdei achilas perasos': ['kdei_achilas_pras'],
		"k'dei achilas perasos": ['kdei_achilas_pras'],
		'kdei achilas prasos': ['kdei_achilas_pras'],
		"k'dei achilas prasos": ['kdei_achilas_pras'],
		'kdei achilat peras': ['kdei_achilas_pras'],
		"k'dei achilat peras": ['kdei_achilas_pras'],
		'kdei achilat perasot': ['kdei_achilas_pras'],
		"k'dei achilat perasot": ['kdei_achilas_pras'],
		'kdei achilat pras': ['kdei_achilas_pras'],
		"k'dei achilat pras": ['kdei_achilas_pras'],
		'kdei achilat prasot': ['kdei_achilas_pras'],
		"k'dei achilat prasot": ['kdei_achilas_pras'],
		'achilas peras': ['kdei_achilas_pras'],
		'achilas pras': ['kdei_achilas_pras'],
		'achilas perasos': ['kdei_achilas_pras'],
		'achilas prasos': ['kdei_achilas_pras'],
		'achilat perasot': ['kdei_achilas_pras'],
		'achilat prasot': ['kdei_achilas_pras'],
		'small onah': ['small_onah'],
		'onah katan': ['small_onah'],
		'onah katans': ['small_onah'],
		'small onos': ['small_onah'],
		'small onot': ['small_onah'],
		'small onahs': ['small_onah'],
		'small onaah': ['small_onah'],
		et: ['et'],
		ait: ['et'],
		eit: ['et'],
		ets: ['et'],
		eits: ['et'],
		etim: ['et'],
		chelek: ['chelek'],
		helek: ['chelek'],
		chalakim: ['chelek'],
		cheleks: ['chelek'],
		chelekim: ['chelek'],
		chelekot: ['chelek'],
		chelekos: ['chelek'],
		helekim: ['chelek'],
		helekot: ['chelek'],
		helekos: ['chelek'],
		part: ['chelek'],
		parts: ['chelek'],
		cheleck: ['chelek'],
		rega: ['rega'],
		regaim: ['rega'],
		regah: ['rega'],
		regas: ['rega'],
		regayim: ['rega'],
		regahs: ['rega'],
		century: ['century'],
		centuries: ['century'],
		decades: ['decade'],
		decade: ['decade'],
		year: ['year'],
		years: ['year'],
		'gregorian years': ['year'],
		'gregorian year': ['year'],
		'regular year': ['year'],
		yr: ['year'],
		yrs: ['year'],
		month: ['month'],
		'gregorian month': ['month'],
		'regular month': ['month'],
		months: ['month'],
		'gregorian months': ['month'],
		'regular months': ['month'],
		mon: ['month'],
		mo: ['month'],
		weeks: ['week'],
		week: ['week'],
		wk: ['week'],
		wks: ['week'],
		d: ['day'],
		day: ['day'],
		days: ['day'],
		dates: ['day'],
		hours: ['hour'],
		'regular hours': ['hour'],
		'standard hours': ['hour'],
		hour: ['hour'],
		'regular hour': ['hour'],
		hr: ['hour'],
		hrs: ['hour'],
		h: ['hour'],
		'standard hour': ['hour'],
		minute: ['minute'],
		minutes: ['minute'],
		min: ['minute'],
		mins: ['minute'],
		m: ['minute'],
		'standard minutes': ['minute'],
		sec: ['second'],
		secs: ['second'],
		second: ['second'],
		seconds: ['second'],
		'standard seconds': ['second'],
		s: ['second'],
		ms: ['millisecond'],
		milliseconds: ['millisecond'],
		millisecond: ['millisecond'],
		msec: ['millisecond'],
		msecs: ['millisecond'],
	},
};
