/** @type {Record<string, Record<string, string[]>>} */
export const zmanimInputs = {
	zmanim: {
		alos: ['alos16Point1', 'alos72'],
		alot: ['alos16Point1', 'alos72'],
		'alot hashachar': ['alos16Point1', 'alos72'],
		'alos hashachar': ['alos16Point1', 'alos72'],
		'עלות השחר': ['alos16Point1', 'alos72'],
		עלות: ['alos16Point1', 'alos72'],
		'alos 16.1 degrees': ['alos16Point1'],
		'alos 16.1°': ['alos16Point1'],
		'alos hashachar 16.1 degrees': ['alos16Point1'],
		'alot 16.1 degrees': ['alos16Point1'],
		'alot hashachar 16.1 degrees': ['alos16Point1'],
		'alos (16.1°)': ['alos16Point1'],
		'alos 72 minutes': ['alos72'],
		'alos hashachar 72 minutes': ['alos72'],
		'alot 72 minutes': ['alos72'],
		'alot hashachar 72 minutes': ['alos72'],
		'alos (72 minutes)': ['alos72'],
		misheyakir: ['misheyakir', 'misheyakirMachmir'],
		dawn: ['misheyakir', 'misheyakirMachmir'],
		'earliest tallis and tefillin': ['misheyakir', 'misheyakirMachmir'],
		'earliest talis and tefilin time': ['misheyakir', 'misheyakirMachmir'],
		'earliest tallit and tefillin': ['misheyakir', 'misheyakirMachmir'],
		'misheyakir machmir': ['misheyakirMachmir'],
		משיכיר: ['misheyakir', 'misheyakirMachmir'],
		'משיכיר מחמיר': ['misheyakirMachmir'],
		sunrise: ['sunrise'],
		netz: ['sunrise'],
		'netz hachama': ['sunrise'],
		neitz: ['sunrise'],
		'neitz hachama': ['sunrise'],
		נץ: ['sunrise'],
		'נץ החמה': ['sunrise'],
		'sof zman shema': ['sofZmanShmaGRA', 'sofZmanShmaMGA'],
		'sof zman shma gra': ['sofZmanShmaGRA'],
		'sof zman shema gra': ['sofZmanShmaGRA'],
		'sof zman shma magen avraham': ['sofZmanShmaMGA'],
		'sof zman shema magen avraham': ['sofZmanShmaMGA'],
		'sof zman shma magen avram': ['sofZmanShmaMGA'],
		'sof zman shma magen avrohom': ['sofZmanShmaMGA'],
		'sof zman kriat shema': ['sofZmanShmaGRA', 'sofZmanShmaMGA'],
		'sof zman krias shema': ['sofZmanShmaGRA', 'sofZmanShmaMGA'],
		'sof zman kriyas shema': ['sofZmanShmaGRA', 'sofZmanShmaMGA'],
		'sof zman kriyat shema': ['sofZmanShmaGRA', 'sofZmanShmaMGA'],
		'sof zman krias shema gra': ['sofZmanShmaGRA'],
		'sof zman kriyas shema gra': ['sofZmanShmaGRA'],
		'sof zman kriyat shema gra': ['sofZmanShmaGRA'],
		'sof zman krias shema magen avraham': ['sofZmanShmaMGA'],
		'sof zman kriyas shema magen avraham': ['sofZmanShmaMGA'],
		'sof zman kriyat shema magen avraham': ['sofZmanShmaMGA'],
		'sof zman krias shema magen avram': ['sofZmanShmaMGA'],
		'sof zman kriyas shema magen avram': ['sofZmanShmaMGA'],
		'sof zman kriyat shema magen avram': ['sofZmanShmaMGA'],
		'sof zman krias shema magen avrohom': ['sofZmanShmaMGA'],
		'sof zman kriyas shema magen avrohom': ['sofZmanShmaMGA'],
		'sof zman shma (gra)': ['sofZmanShmaGRA'],
		'sof zman shma (mga)': ['sofZmanShmaMGA'],
		'סוף זמן שמע': ['sofZmanShmaGRA', 'sofZmanShmaMGA'],
		'סוף זמן שמע (גר"א)': ['sofZmanShmaGRA'],
		'סוף זמן שמע (מג"א)': ['sofZmanShmaMGA'],
		'סוף זמן קריאת שמע': ['sofZmanShmaGRA', 'sofZmanShmaMGA'],
		'sof zman tfilla': ['sofZmanTefillaGRA', 'sofZmanTefillaMGA'],
		'sof zman tefilla': ['sofZmanTefillaGRA', 'sofZmanTefillaMGA'],
		'sof zman tefillah': ['sofZmanTefillaGRA'],
		'sof zman tefila': ['sofZmanTefillaGRA'],
		'sof zman tefilla gra': ['sofZmanTefillaGRA'],
		'sof zman tefilla magen avraham': ['sofZmanTefillaMGA'],
		'sof zman tefilla magen avram': ['sofZmanTefillaMGA'],
		'sof zman tefilla magen avrohom': ['sofZmanTefillaMGA'],
		'sof zman tefilla (gra)': ['sofZmanTefillaGRA'],
		'sof zman tefilla (mga)': ['sofZmanTefillaMGA'],
		'סוף זמן תפילה': ['sofZmanTefillaGRA', 'sofZmanTefillaMGA'],
		'סוף זמן תפילה (גר"א)': ['sofZmanTefillaGRA'],
		'סוף זמן תפילה (מג"א)': ['sofZmanTefillaMGA'],
		chatzos: ['chatzos'],
		noon: ['chatzos'],
		midday: ['chatzos'],
		chatzot: ['chatzos'],
		'chatzot hayom': ['chatzos'],
		חצות: ['chatzos'],
		'חצות היום': ['chatzos'],
		'mincha gedola': ['minchaGedola'],
		'mincha gedolah': ['minchaGedola'],
		mincha: ['minchaGedola', 'minchaKetana', 'plagHamincha'],
		'mincha ketana': ['minchaKetana'],
		'mincha katanah': ['minchaKetana'],
		'mincha katan': ['minchaKetana'],
		'mincha ketanah': ['minchaKetana'],
		מנחה: ['minchaGedola', 'minchaKetana', 'plagHamincha'],
		'מנחה גדולה': ['minchaGedola'],
		'מנחה קטנה': ['minchaKetana'],
		'plag hamincha': ['plagHamincha'],
		'plag haminchah': ['plagHamincha'],
		plag: ['plagHamincha'],
		פלג: ['plagHamincha'],
		'פלג המנחה': ['plagHamincha'],
		sunset: ['sunset'],
		shkiya: ['sunset'],
		shkiyah: ['sunset'],
		'shkiat hachama': ['sunset'],
		'shkiat hachamah': ['sunset'],
		'shkias hachamah': ['sunset'],
		'shkias hachama': ['sunset'],
		shekiah: ['sunset'],
		shekia: ['sunset'],
		'shekias hachama': ['sunset'],
		'shekias hachamah': ['sunset'],
		'shekiyat hachama': ['sunset'],
		'shekiyat hachamah': ['sunset'],
		shekiyah: ['sunset'],
		shekiya: ['sunset'],
		'shekiyas hachama': ['sunset'],
		'shekiyas hachamah': ['sunset'],
		'שקיעת החמה': ['sunset'],
		שקיעה: ['sunset'],
		tzeis: ['tzeis3Stars', 'tzeis3MediumStars', 'tzeis72'],
		'tzeis 3 stars': ['tzeis3Stars'],
		'tzeis 3 medium stars': ['tzeis3MediumStars'],
		'tzeis 72 minutes': ['tzeis72'],
		'tzeis (3 stars)': ['tzeis3Stars'],
		'tzeis (3 medium stars)': ['tzeis3MediumStars'],
		'tzeis (72 minutes)': ['tzeis72'],
		tzeit: ['tzeis3Stars', 'tzeis3MediumStars', 'tzeis72'],
		'tzeit 3 stars': ['tzeis3Stars'],
		'tzeit 3 medium stars': ['tzeis3MediumStars'],
		'tzeit 72 minutes': ['tzeis72'],
		'tzeit (3 stars)': ['tzeis3Stars'],
		'tzeit (3 medium stars)': ['tzeis3MediumStars'],
		'tzeit (72 minutes)': ['tzeis72'],
		'tzeis hakochavim': ['tzeis3Stars', 'tzeis3MediumStars', 'tzeis72'],
		'tzeit hakochavim': ['tzeis3Stars', 'tzeis3MediumStars', 'tzeis72'],
		'צאת הכוכבים': ['tzeis3Stars', 'tzeis3MediumStars', 'tzeis72'],
		צאת: ['tzeis3Stars', 'tzeis3MediumStars', 'tzeis72'],
		'צאת הכוכבים (3 כוכבים)': ['tzeis3Stars'],
		'צאת הכוכבים (3 כוכבים בינוניים)': ['tzeis3MediumStars'],
		'צאת הכוכבים (72 דקות)': ['tzeis72'],
	},
	events: {
		'candle lighting': ['candleLighting'],
		'candle lighting time': ['candleLighting'],
		'הדלקת נרות': ['candleLighting'],
		havdalah: ['havdalah'],
		'end of shabbos': ['havdalah'],
		'end of shabbat': ['havdalah'],
		'the end of shabbos': ['havdalah'],
		'the end of shabbat': ['havdalah'],
		'מוצאי שבת': ['havdalah'],
		'מוצאי שבת קודש': ['havdalah'],
		'the end of yom tov': ['havdalah'],
		הבדלה: ['havdalah'],
		'fast begins': ['fastBegins'],
		'the fast': ['fastBegins'],
		'the beginning of the fast': ['fastBegins'],
		'beginning of the fast': ['fastBegins'],
		'beginning of fast': ['fastBegins'],
		'the fast start': ['fastBegins'],
		'the fast begin': ['fastBegins'],
		צום: ['fastBegins'],
		'תחילת הצום': ['fastBegins'],
		'תחילת תענית': ['fastBegins'],
		'תחילת התענית': ['fastBegins'],
		'fast ends': ['fastEnds'],
		'end of the fast': ['fastEnds'],
		'end of fast': ['fastEnds'],
		'the end of the fast': ['fastEnds'],
		'the fast over': ['fastEnds'],
		'סוף הצום': ['fastEnds'],
		'סוף התענית': ['fastEnds'],
		'סוף תענית': ['fastEnds'],
	},
	durations: {
		'shaah zmanis': ['shaahZmanisGRA', 'shaahZmanisMGA'],
		'shaah zmanit': ['shaahZmanisGRA', 'shaahZmanisMGA'],
		'shaot zmaniyot': ['shaahZmanisGRA', 'shaahZmanisMGA'],
		'shaah zmanit (gra)': ['shaahZmanisGRA'],
		'shaah zmanit (mga)': ['shaahZmanisMGA'],
		'שעה זמנית': ['shaahZmanisGRA', 'shaahZmanisMGA'],
		'שעה זמנית (גר"א)': ['shaahZmanisGRA'],
		'שעה זמנית (מג"א)': ['shaahZmanisMGA'],
		'שעות זמניות': ['shaahZmanisGRA', 'shaahZmanisMGA'],
		'shaah zmanis gra': ['shaahZmanisGRA'],
		'shaah zmanis mga': ['shaahZmanisMGA'],
		'shaah zmanis (gra)': ['shaahZmanisGRA'],
		'shaah zmanis (mga)': ['shaahZmanisMGA'],
		shaah: ['shaahZmanisGRA', 'shaahZmanisMGA'],
		hour: ['shaahZmanisGRA', 'shaahZmanisMGA'],
		'halachic hour': ['shaahZmanisGRA', 'shaahZmanisMGA'],
		'halachik hour': ['shaahZmanisGRA', 'shaahZmanisMGA'],
	},
};
